import React from 'react'

function Privacy() {
  return (
    <div className='p-8'> 
<p className='text-2xl mb-3'> Privacy Policy</p>    
We value the trust you place in us and recognize the importance of information privacy. This privacy policy (“Privacy Policy”) describes how xwealth collects, uses, shares, stores or otherwise processes your personal information through the xwealth Group Corporate website https://corporate.xwealth.net, m-site (hereinafter to as the “Platform”).
While you may be able to browse the Platform across the globe without registering with us or without sharing any personal information, in case you voluntarily share your personal information, it will primarily be stored and processed in India and may have data protection laws that are different from those that apply in the country in which you are located. By visiting this Platform, you expressly agree to be bound by the terms and conditions of this Privacy Policy, the Terms of Use and agree to be governed by the laws of India including but not limited to the laws applicable to data protection and privacy. If you do not agree please do not use or access our Platform.
<p className='text-2xl mb-3'>Collection of your Information</p>
When you browse the content or use the Platform or connect with us, we do not collect any information about you. In general, you can browse the Platform without telling us who you are or revealing any personal information about yourself. However, in case you voluntarily provide your personal information to us, you will not be anonymous to us and your personal information will be processed as per applicable laws in India. Please refrain from providing any personal information including sensitive personal information in case you try to contact us directly on the email.
If you send us any personal correspondence, such as emails or letters, we may collect such information into a file specific to you and stored in a server of our discretion.
<p className='text-2xl mb-3'>Use of your Information</p>
We identify and use your IP address to help diagnose problems with our server, and to administer our Platform. Your IP address may be used to identify you and to gather broad information. We may also use your information for legal or regulatory purposes or reach out back to you in case of any potential business opportunities.
We may process certain information of the website’s visitors and analyze it on an aggregated basis. This information may include the URL that you just came from (whether this URL is on our Platform or not), which URL you next go to (whether this URL is on our Platform or not), your computer browser information, and your IP address. For clarity, and notwithstanding anything contained herein, all interactions and transactions outside our Platform are expressly disclaimed from our responsibility or liability (of any kind).
<p className='text-2xl mb-3'>Cookies</p>
We use data collection devices such as "cookies" on certain pages of the Platform to help analyze our web page flow, and promote trust and safety. "Cookies" are small files placed on your hard drive that assist us in providing our services. Cookies do not contain any of your personal information. Additionally, you may encounter "cookies" or other similar devices on certain pages of the Platform that are placed by third parties. We do not control the use of cookies by third parties. You can also control the use of cookies at the individual browser level, but if you choose to disable cookies, it may limit your use of certain features or functions on the services.
<p className='text-2xl mb-3'>Sharing of Personal Information</p>
We may share personal information internally within xwealth group companies, affiliates, related companies and with other third parties for the purpose of providing services offered by them and in general connection to use of this Platform.
We may share these information internally with our xwealth Group companies, affiliates, related companies for enhancing user experience; for responding to your queries; to comply with our legal obligations; to enforce our Terms of Use; to analyze data on an aggregated level; for identifying any potential business opportunities, which may include schemes and plans which we find relevant to you and your requirements. We may also share these information in case of any mergers, acquisitions or amalgamations; to prevent, detect, mitigate, and investigate fraudulent or illegal activities related to activity in the Platform. We may disclose personal information with law enforcement agencies, third party right owners, if required to do so by law or in the good faith belief that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal process. However, we do not disclose your personal information to unrelated third parties for their marketing and advertising purposes without your explicit consent.
<p className='text-2xl mb-3'>Link to other Sites</p>
Our Platform may provide links to other websites from our xwealth Group companies or applications that may collect personal information about you. We suggest reviewing their respective Privacy Policies to understand their Privacy obligations before sharing any information.
<p className='text-2xl mb-3'>Security Precautions</p>
We maintain reasonable physical, electronic and procedural safeguards to protect your information. Once your information is in our possession, we adhere to our security guidelines to protect it against unauthorized access. However, by using the Platform, the users accept the inherent security implications of data transmission over the internet and the World Wide Web which cannot always be guaranteed as completely secure, and therefore, there would always remain certain inherent risks regarding use of the Platform.
<p className='text-2xl mb-3'>Children Information</p>
Use of our Platform is available only to persons who can form a legally binding contract under applicable law. We do not knowingly solicit or collect personal information from children under the age of 18 years. If you have shared any personal information of children under the age of 18 years, you represent that you have the authority to do so and permit us to use the information in accordance with this Privacy Policy.
<p className='text-2xl mb-3'>Data Retention</p>
We retain your personal information in accordance with applicable laws, for a period no longer than is required for the purpose for which it was collected or as required under the applicable law. However, we may retain data related to you if we believe it may be necessary to prevent fraud or future abuse, to enable xwealth to exercise its legal rights and/or defend against legal claims or if required by law or for other legitimate purposes.
<p className='text-2xl mb-3'>Your Rights</p>
We take every reasonable step to ensure that your personal information that we process is accurate and, where necessary, kept up to date, and any of your personal information that we process that you inform us is inaccurate (having regard to the purposes for which they are processed) is erased or rectified. Please contact us using the details below in case you want to exercise any ‘Data Subject Rights’ as per the applicable laws.
<p className='text-2xl mb-3'>Your Consent</p>
By visiting our Platform or by voluntarily providing your information, you consent to the collection, use, storage, disclosure and otherwise processing of your information on the Platform in accordance with this Privacy Policy. If you disclose to us any personal information relating to other people, you represent that you have the authority to do so and to permit us to use the information in accordance with this Privacy Policy.
<p className='text-2xl mb-3'>Changes to this Privacy Policy</p>
Please check our Privacy Policy periodically for changes. We may update this Privacy Policy to reflect changes to our information practices.
<p className='text-2xl mb-3'>Grievance Officer</p>
<address>add address </address>
    </div>
  )
}

export default Privacy